services:
  structuredlogging:
    container_name: structuredlogging
    build: .
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_URLS=http://+:5001
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201" # Logstash UDP input port
        tag: "structuredlogging"
    restart: always