services:
  elasticsearch:
    image: elasticsearch:8.4.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - ./assets/elastic/data/:/usr/share/elasticsearch/data
    mem_limit: "1g"

  fluentbit:
    image: fluent/fluent-bit
    volumes: 
      - ./assets/fluent:/fluent-bit/etc/
    ports: 
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.4.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch